### ISSUE TITLE
Dozens of questions a day regarding the lovelace.html file

### ISSUE THREAD

**Issue by JAOverbay** [learn-co-curriculum/selecting-single-elements-readme#17]
I believe in the reading you should reference the button for github to download the link and perhaps include a little image of the button so that students know what to look for. The reading is not clear on the subject and just says to download the html file included in the reading.

**Comment by sgharms** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process
but thank you for helping us ensure that those who follow in your path will not
encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this
issue.

Sincerely,

Flatiron Curriculum Team

**Comment by bhollan** [comment]
I think it's a much better idea to serve the repo's `lovelace.html` file to a `github.io` page from a `gh-pages` branch or something.  I still don't think this is headed in the right direction.

**Comment by FernanGonzalez** [comment]
I just arrived here because of the same issue. I was looking for a button or something in the text to find lovelace.html.

The text reads (the bold letters are mine):

> We have copied the HTML from a page on Ada Lovelace from Wikipedia and simplified it a bit. Open the lovelace.html page **included in this reading in your web browser**.

It does not say anywhere that it's on GitHub and this is the first time we have to use a file from there in the Accelerated Bootcamp Prep. I think some pointers would be helpful :).

**Comment by FernanGonzalez** [comment]
I see they have updated it and the changes show now, now there's a beautiful ZIP file with everything we need for this lab. Thank you! :).

**Comment by sgharms** [comment]
Sweet @FernanGonzalez!

@bhollan seems pretty reasonable. I'll look into it as a long-term fix. Otherwise, happy weekend!
